ARG DOCKER_REGISTRY=docker.io
ARG DOCKER_IMG_TAG=":2018-09-10_08-58_df02a2f817d1"
ARG DOCKER_IMG_HASH=""
FROM ${DOCKER_REGISTRY}/qnib/alplain-init${DOCKER_IMG_TAG}${DOCKER_IMG_HASH}

RUN apk --no-cache add openjdk8-jre
